### ISSUE TITLE
ui-select2 doesn't work in IE8

### ISSUE THREAD

**Issue by jdlaroche** [angular-ui/angular-ui-OLDREPO#289] opened 2012-12-04 19:00 UTC
When you try to use ui-select2 in IE8, you receive the following error : object doesn't support this property or method <select ui-select2 ng-model="abc">.

The problem is that IE doesn't support the String.trim() method called on line 878 (watch = repeatAttr.split('|')[0].trim().split(' ').pop();)

I fixed this by adding this script in my page :

if(typeof String.prototype.trim !== 'function') {
  String.prototype.trim = function() {
    return this.replace(/^\s+|\s+$/g, ''); 
  }
}

**Comment by ProLoser** [comment] 2012-12-04 22:45
Duplicate of #253

A new build needs to be pushed with the fix.

**Closed as completed by ProLoser** 2012-12-04 22:45 UTC
