### ISSUE TITLE
Sortable directive

### ISSUE THREAD

**Issue by max-mykhailenko** [angular-ui/angular-ui-OLDREPO#460] opened 2013-02-25 11:39 UTC
Sortable directive not always changes position of elements in array. Try to move the first element to middle position. If I move element up in the list directive works right, but if I move it down nothing changes in array

**Comment by kofalt** [comment] 2013-02-25 21:55
+1 on this. You can reproduce the problem on angular-ui's home page.

Attached are a series of screenshots showing:
- The initial state
- Strange behavior when trying to drag the "Anna" parent 
  - _letting go of the mouse here placed Anna back in the first position_
- A broken state - the list does not update the model 
  - _Anna has been successfully moved but the model has not changed_

![image](https://f.cloud.github.com/assets/265071/193899/76b54734-7f95-11e2-836d-79943e665444.png)
![image](https://f.cloud.github.com/assets/265071/193902/84e055b0-7f95-11e2-8d80-c978b328d991.png)
![image](https://f.cloud.github.com/assets/265071/193903/91fa5390-7f95-11e2-8ace-eef34f1255e5.png)

**Comment by sergiokozlov** [comment] 2013-03-05 10:23
I faced the same issue. This is more detailed use case:
- When you move element on **two** or more positions **down** - everything works fine
- When you move element on **any** number of positions **up** - everything works fine
- When you do move element on **one** position **down** - ui is updated however underlying ng-model isn't

Please see fiddle that allows to easily reproduce the problem: http://jsfiddle.net/sergiokozlov/suFqw/6/

**Comment by Drane** [comment] 2013-03-05 10:50
FYI, also stumbled upon this issue. 
Any idea's where the problem is situated? If not, perhaps I'll try to narrow it down and post useful stuff here if I might find anything useful. grts

**Comment by sergiokozlov** [comment] 2013-03-05 12:15
I found similar issue that was closed: https://github.com/angular-ui/angular-ui/issues/433  by @skahlert, however it seems that his fixed didn't solve the problem

**Comment by kofalt** [comment] 2013-03-05 12:24
For @JochenSzostek or anyone on the bughunt, the problem is likely situated in the directive's file, [sortable.js](https://github.com/skahlert/angular-ui/blob/master/modules/directives/sortable/sortable.js).

At a guess, the problem might be around [line 27](https://github.com/skahlert/angular-ui/blob/master/modules/directives/sortable/sortable.js#L27), which appears to be the update handler:

``` javascript
          onUpdate = function(e, ui) {
            // For some reason the reference to ngModel in stop() is wrong
            ui.item.sortable.resort = ngModel;
          };
```

That's a curious comment, made by @ProLoser in 4fcebce288c9706ee5409b583cac0093d8837489. I haven't had time to dive further into this yet.

**Comment by skahlert** [comment] 2013-03-05 12:34
I think the minified version has not yet the fix included.

**Comment by skahlert** [comment] 2013-03-05 12:37
I forked the Fiddle here, with the source-files... seems to work:
http://jsfiddle.net/JfgX8/

**Comment by sergiokozlov** [comment] 2013-03-05 12:43
@skahlert Try to change **one** and **two** (drag **one** behind **two**) and you will see that ngModel is not updated

**Comment by skahlert** [comment] 2013-03-05 12:50
Oh, silly me...
I forgot to save the patch...
try again:
http://jsfiddle.net/JfgX8/1/

**Comment by sergiokozlov** [comment] 2013-03-05 12:57
Great, It works!I will use source-files while the min version in master is out of date.

Thank you a lot for the help! It really helps.

**Comment by ThomasDeutsch** [comment] 2013-03-13 16:40
When i use inline-block elements, i get some problems that seems like performance problems:
http://jsfiddle.net/hKYWr/287/
If you move an element a bit around, you will see that it will not get fitted in.

Not in this sample without Angular
http://jsfiddle.net/johni/8UQVp/

Maybe, it is because of missing placeholders.
But how can i set up placeholders?

**Comment by jilljenn** [comment] 2013-03-17 15:28
I think there is a problem with the update function as well. It seems to be called before the actual reorder of the sortable:
http://jsfiddle.net/Le_Sphinx/hKYWr/400/

**Comment by aroneous** [comment] 2013-03-20 05:54
The issue appears to be related to this bit in the onStop handler:

```
if (start < end)
  end--;
```

At least in the simple case I'm testing, the end position is already correct without decrementing it.

**Comment by ProLoser** [comment] 2013-05-03 09:16
AngularUI is currently undergoing a restructure. This project will no longer hold the codebase, can you please relocate this to https://github.com/angular-ui/ui-sortable (after confirming it's still necessary with the latest code)?

**Comment by kofalt** [comment] 2013-05-03 15:57
Just to confirm - a clean build of the source fixes this so as long as the new ui-sortable repo has a correct upload it should be fixed.

**Comment by ProLoser** [comment] 2013-05-03 17:48
@kofalt So should I close this?

**Comment by kofalt** [comment] 2013-05-03 20:31
Since there doesn't currently appear to be any library downloads on http://angular-ui.github.io/, this should be fixed as long as future builds use the latest code. :+1:

**Closed as completed** 2013-05-03 23:03 UTC
