### ISSUE TITLE
Select2 crashes when no ngMultiple option set

### ISSUE THREAD

**Issue by Letsan** [angular-ui/angular-ui-OLDREPO#276] opened 2012-11-22 14:24 UTC
Hi,

I have run across a bug a few times but I have a hard time reproducing it. 

I have a Item Details page which allows to edit the Item's properties and then save them to the backend. Some of the details are select2 selects.
When the user opens the details page, the app loads the items data from the backend based on the URL. Data then gets populated in the different inputs of the page using ng-model. Strangely, sometimes select2 just fails to load (even though the select options are still loaded) and I get a normal select box instead.
Options are passed with an ng-repeat iterating over an array, and there's an empty option at the beginning for the placeholder.

The error shown is below, and the lines who cause the problem are these ones:

``` javascript
scope.$watch(attrs.ngMultiple, function(newVal) {
     elm.select2(opts);
});
```

Apparently the ui-select2 directive is trying to read the ngMultiple attribute of the select, when there's none to be read!
When I add ng-multiple="false" to the select2 element, the select2 works as expected. (see image here, the only select2 with ngMultiple set works great).
http://www.rodrigochiong.com/temp/Shot22.jpg

I don't know if there's a way to fix this, or maybe we should enforce people to declare ngMultiple in their selects.
Sadly I can't put up a fiddle beacuse it happens from time to time (I don't know the cause of it, maybe how data is loaded or how much time does the backend take to respond ?).

Error shown in console:

```
TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (http://ncerchiongrayo.nce.amadeus.net/scrum/#/stories/6:319:19)
    at Object.$delegate.__proto__.$watch (http://ncerchiongrayo.nce.amadeus.net/scrum/#/stories/6:351:28)
    at http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular-ui.js:946:15
    at nodeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:4222:13)
    at compositeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:3834:14)
    at nodeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:4216:24)
    at compositeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:3834:14)
    at compositeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:3837:12)
    at nodeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:4216:24)
    at compositeLinkFn (http://ncerchiongrayo.nce.amadeus.net/scrum/lib/angular/angular.js:3834:14) <select class="input-xlarge ng-pristine ng-valid" ng-model="story.parentId" ui-select2="{allowClear: true}" data-placeholder="Select parent story..."> 
```

**Comment by ProLoser** [comment] 2012-12-08 00:44
Duplicate of #274

**Closed as completed by ProLoser** 2012-12-08 00:44 UTC
