### ISSUE TITLE
most excellent refactoring of modal

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#50] opened 2012-07-12 15:57 UTC
@ajoslin Andy, much much better. I'm going to try and work it into code at work. How'd you come up with the $$phase bit? One comment I might make is to do something like below. I think it follows better practices wrapping function in $apply.

```
      if (!scope.$$phase) {
        scope.$apply(function() {
            model.$setViewValue(false);
        });
      }
```

**Comment by ajoslin** [comment] 2012-07-12 16:07
I saw one of the angular devs mention $$phase on the google group one time.  The problem is that the close event could be fired when a $digest is already going, or it could be fired when one isn't going.

When someone clicks an `<a ng-click="myModalShown = false">`, the ng-click will trigger a $digest and all is good, we don't need an $apply.

But the modal could also be closed outside angular through something like `<a data-dismiss="modal" href="#myModal">`, and we do need an $apply here.

scope.$$phase is null when there's no apply/digest going, and is some string otherwise.  I can either check $$phase, or use $timeout as Peter suggested:

``` javascript
$timeout(function() { model.$setViewValue(false); });
```

The problem is, $timeout was giving me weird bugs in my tests (because it's async and I don't know how to do async tests), so I just ditched it in favor of $$phase.  

Anyway, the change sounds right.. I only did it that way so I wouldn't have to repeat myself, since you need something if the scope is already being digested.  But  you're right, it's really better to have the function in apply:

``` javascript
function setModel() { 
  model.$setViewValue(false);
};
if (!scope.$$phase) scope.$apply(setModel);
else setModel();
```

**Comment by dandoyon** [comment] 2012-07-12 16:09
I'll g

**Comment by petebacondarwin** [comment] 2012-07-12 16:24
Just be warned that $$phase is not a public API and so cannot be relied upon in the future.
That being said there ought to be a standard (AngularJS supported) pattern for dealing with this situation as it does appear a lot.

**Comment by dandoyon** [comment] 2012-07-12 18:11
I fully agree that $$phase should not be the mechanism. I tried with $timeout (your suggestion) and it works fine. Hoping to hear from googlegroup on how to unit test with $timeout mock.

**Comment by ProLoser** [comment] 2012-07-15 11:13
Closing this since I believe the latest uses $timeout now. Feel free to reopen if incorrect.

**Closed as completed by ProLoser** 2012-07-15 11:13 UTC
Labels: question
