### ISSUE TITLE
example validate highlight

### ISSUE THREAD

**Issue by johannesjo** [angular-ui/angular-ui-OLDREPO#418] opened 2013-02-12 01:04 UTC
Just recognized that in a fast click through ( i apologize if this has been reported before) that while the validation for email works correctly the outline of the input already gets blue again after '@' and any other letter is typed.

Imho validation status and appearance should be strictly linked to each other in this case anyway.

**Comment by ProLoser** [comment] 2013-02-12 07:59
Duplicate of #416

**Closed as completed by ProLoser** 2013-02-12 07:59 UTC
