### ISSUE TITLE
Scope not updating with ui-mask

### ISSUE THREAD

**Issue by jameswyse** [angular-ui/angular-ui-OLDREPO#152] opened 2012-08-14 07:45 UTC
Hi guys,

I've been using angular-ui for a while and I love it, it's a fantastic idea. 

I tried to use ui-mask today and visually it's working, however it's not updating the scope via ng-model. It seems like a bug, but perhaps I'm doing something wrong.

Here's a JSBin example with both a normal input and one using ui-mask: http://jsbin.com/udayah/6/edit (copied it from another issue, thanks for that)

Cheers 8)

**Comment by petebacondarwin** [comment] 2012-08-14 08:06
I suspect you are using the wrong version of the jquery mask plug in. There
is a hacked version that must be used. Look at the source on the angular-ui
demo page.

Pete
...from my mobile.

**Comment by jameswyse** [comment] 2012-08-14 08:12
I used the exact file from the demo in my project, and also used it directly in my JSBin example. 
This one: http://angular-ui.github.com/lib/maskedinput/src/jquery.maskedinput.js

The script used in the demo is the same as the original: http://digitalbush.com/projects/masked-input-plugin if a hacked one is required then the demo doesn't seem to be using it?

**Comment by petebacondarwin** [comment] 2012-08-14 09:12
That is probably right.

Pete
...from my mobile.

**Comment by jameswyse** [comment] 2012-08-16 02:36
So any ideas on this?

**Comment by ajoslin** [comment] 2012-08-17 00:25
Pete's on vacation right now, afaik.  @everyone, anyone else have knowledge of this directive?

**Comment by jameswyse** [comment] 2012-08-17 03:49
This may provide some insight, running my JSBin and taking a look using Batarang: http://imgur.com/UFbdt

This seems to be a problem I'm running in to fairly often where new scopes are being created out of nowhere. I'm still pretty new to AngularJS so sorry I'm not much help here!

I did notice the masked input has these classes defined in the DOM with a perfectly valid mask value, which struck me as odd: 

`ng-isolate-scope ng-scope ng-dirty ng-invalid ng-invalid-mask`

**Comment by petebacondarwin** [comment] 2012-08-17 06:18
Hi James

The version it needs is
https://raw.github.com/twarogowski/angular-contrib/master/js/lib/jquery.maskedinput-1.3.js.
 But I have played around and I am not sure this is the problem.

The angular ui demo is not correct.

I am on vacation so it is a bit tricky to dig into this.

Pete

**Comment by jameswyse** [comment] 2012-08-18 04:18
Hi Pete, yeah that doesn't seem to make any difference. But anyway, Github != Vacation, go have some fun! :D

**Comment by ldiego08** [comment] 2012-08-23 15:53
I am also experiencing this issue. Is actually acting as a blocker for my project. :/

**Comment by jameswyse** [comment] 2012-08-23 15:56
I'm in crunch mode to get a project finished right now (going on vacation too!) but it's only a minor thing for this project so I've had to ignore it for now. If I get some time I'll take a stab at getting it working..

**Comment by ldiego08** [comment] 2012-08-23 15:58
Thank you, James. It would be very much appreciated. I'll try to fix it by myself for now.

**Comment by petebacondarwin** [comment] 2012-08-23 16:05
Hi guys
I am sorry I don't have access to be able to look at this right now as I am
away till 1 Sept. I am sure it was working not long ago so you could try
looking through the git history for the directive to see if something broke
it.
If your project is commercial and this is blocking it, you may consider
advertising on the main angular mailing lists to pay someone to solve the
problem.

Pete
...from my mobile.

**Comment by pkozlowski-opensource** [comment] 2012-08-23 17:05
I'm going to look into this issue, I hope I will be able to figure out what is going on here.

**Comment by ldiego08** [comment] 2012-08-23 17:34
Thank you, Pawel. I already tried to look for changes with previous versions of the source file. The code seems to be the same in all versions. I found however that the `isValid()` function is missing in the uimask plugin version 1.3 which is making the `isValid = element.data('mask-isvalid')` to evaluate as `undefined`. Adding the `isValid` function back to the uimask plugin source file seems to solve that but the scope is still not updating.

Hope that helps a bit.

**Comment by petebacondarwin** [comment] 2012-08-23 17:42
You need a completely different version of the widget from 1.3

Pete
...from my mobile.

**Comment by ldiego08** [comment] 2012-08-23 17:43
I grabbed the version used by the demo site.

**Comment by pkozlowski-opensource** [comment] 2012-08-23 18:26
OK, so my findings so far:
- this directive is using an isolated scope and I guess that the setup of this scope is not right... this is why the value is not updated
- removing an isolated scope (for testing) gives me this error: 

TypeError: undefined is not a function
    at $.fn.extend.mask (https://raw.github.com/twarogowski/angular-contrib/master/js/lib/jquery.maskedinput-1.3.js:57:39)

@petebacondarwin do we really need isolated scope here?

**Comment by petebacondarwin** [comment] 2012-08-23 18:45
No

Pete
...from my mobile.

**Comment by petebacondarwin** [comment] 2012-08-23 18:49
I think the problem may well be to do with the event used to trigger the
model update. The working version in my app uses onblur rather than change
or key up.
As well as using the correct js file

Pete
...from my mobile.

**Comment by ProLoser** [comment] 2012-08-23 19:21
What is the purpose of the isolate scope though, it seems unnecessary?

Also, not sure if you're aware @petebacondarwin but we found out a couple of weeks ago that angular doesn't actually monitor the `change` event by default (on modern browsers) but instead monitors the `input` event which is the "new-hawtness" and recommended by the w3. I think @pkozlowski-opensource found this out when poking around the source when we were upgrading the passthru. I'm not sure if that's relevant at all.

**Comment by pkozlowski-opensource** [comment] 2012-08-23 19:33
OK guys, I think I got it working, just pushed a fix into branch issue152, see this commit: ace6aeb700.
@ldiego08,  @jameswyse, would it be possible for you to test with those changes? Just grab sources from the commit.
I will be on the #angularjs IRC if needed.

As far as I understand there were 2 issues:
- isolated scope
- the way of checking validity of the masked value

I will look more into this directive while adding tests. When this is done I will open a proper PR.

@petebacondarwin I'm sorry, but I've checked it in JS...

**Comment by ldiego08** [comment] 2012-08-23 19:43
Great!! I'll test right away. Thanks.

**Comment by petebacondarwin** [comment] 2012-08-23 19:44
No worries but do delete the coffeescript so there is no confusion. Thanks
for sorting this out.

... sent from my tablet

**Comment by ldiego08** [comment] 2012-08-23 19:49
Alright. Is working for me now.

**Comment by pkozlowski-opensource** [comment] 2012-08-23 20:13
@ldiego08 Luis, thnx for testing. I will add tests now and will send a proper PR. But I hope that you are at least now.

**Comment by ldiego08** [comment] 2012-08-23 20:18
Sure, Pawel, no problem. This will do for now. Thanks, you saved me some trouble.

**Comment by jigneshjdesai** [comment] 2012-11-07 21:49
I have got v.0.3.0, but still having this issue in my project. Can anyone help please?

**Comment by pkozlowski-opensource** [comment] 2012-11-07 22:53
Try to post a jsFiddle / plunker with a reproduce scenario and steps
to reproduce. There might be a bug somewhere but if we can reproduce
it we can't fix it :-(

**Comment by jigneshjdesai** [comment] 2012-11-08 16:47
Here is the jsFiddle - http://jsfiddle.net/jigneshjdesai/9sTtV/14/

I am trying to format a phone number as (999) 999-9999 in the input text box.

**Comment by pkozlowski-opensource** [comment] 2012-11-08 16:55
@jigneshjdesai Here is a working jsFiddle: http://jsfiddle.net/tAGeM/1/

What you need to observe is the fact that the `ui-mask` directive accepts a mask as an expression and not as string. So, if you want to use a raw string you need to quote it like so: `ui-mask="'(999) 999-9999'"`

This behavior is consistent with other AngularJS directives accepting expressions.

**Closed as completed by pkozlowski-opensource** 2012-11-08 16:55 UTC

**Comment by jigneshjdesai** [comment] 2012-11-08 17:01
oh, that was it? 

Thanks for looking into my such silly and stupid problem.

**Comment by pkozlowski-opensource** [comment] 2012-11-08 17:06
@jigneshjdesai No worries... Next time try to post first on the mailing list (`angular-ui@googlegroups.com`) if you are not sure if you are dealing with a bug. Also attaching a jsFiddle makes it possible to help really quickly...

**Comment by calebmadrigal** [comment] 2013-04-04 20:12
Using a version of jQuery older than 1.9 fixed my problem.  Here was the issue which was breaking my data binding when using ui-mask: http://stackoverflow.com/questions/14793331/uncaught-typeerror-cannot-read-property-msie-of-undefined.
