### ISSUE TITLE
Select 2 with fetched model values

### ISSUE THREAD

**Issue by mpaulucci** [angular-ui/angular-ui-OLDREPO#278] opened 2012-11-27 14:20 UTC
Hi, I'm using select2 with models that I'm fetching with $resource. There seems to be a bug related when the plugin is initialized before the data comes from the servers, so the select2 does not show the initial values.

Here is a plunkr to illustrate the issue:

 http://plnkr.co/edit/ZgT3IR

Is there a way to manually tell the select2 to use this value?

Thanks!

**Comment by ProLoser** [comment] 2012-11-27 18:20
Looks like this may be a duplicate of #263

**Comment by mpaulucci** [comment] 2012-11-27 18:58
I looked at that issue before posting, and if I'm correct the issues are similar but not exactly the same. 

In fact the proposed fix for #263 wouldn't solve this issue, because it is a fix for a select multiple.

**Comment by ProLoser** [comment] 2012-11-27 20:50
I don't follow you. This fix should resolve your problem.

On Tue, Nov 27, 2012 at 10:58 AM, Martin Paulucci
notifications@github.comwrote:

> I looked at that issue before posting, and if I'm correct the issues are
> similar but not exactly the same.
> 
> In fact the proposed fix for #263https://github.com/angular-ui/angular-ui/issues/263wouldn't solve this issue, because it is a fix for a select multiple.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/angular-ui/angular-ui/issues/278#issuecomment-10771440.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser

**Comment by mpaulucci** [comment] 2012-11-27 21:05
```
          if (!isSelect) {
            // Set the view and model value and update the angular template manually for the ajax/multiple select2.
            elm.bind("change", function () {
              scope.$apply(function () {
                controller.$setViewValue(elm.select2('data'));
              });
            });

            // HERE IS THE FIX
            if (opts.initSelection) {
              var initSelection = opts.initSelection;
              opts.initSelection = function (element, callback) {
                initSelection(element, function (value) {
                  controller.$setViewValue(value);
                  callback(value);
                });
              };
            }
          }
```

In my code( angular ui @version v0.2.1 - 2012-09-19) `!isSelect` returns `false`, so the code where the fix goes is never executed. So I presume that that fix wouldn't change anything in my example. Am I missing something?

**Comment by ProLoser** [comment] 2012-11-27 23:23
Ah right. This is a different case though. I will have to dig around to
resolve this.

**Comment by ProLoser** [comment] 2012-12-08 00:52
Your plunker uses `ng-options`, which (as stated on the demo page) `ui-select2` explicitly does NOT support (due to weird-ass timing bugs).

This is the same plunker using `ng-repeat` http://plnkr.co/edit/IoNTyT?p=preview and it seems to work perfectly.

You actually can't/shouldn't use `initSelection` when in `<select>` mode because the bottom line is there's no "initilization" logic involved. You simply set the plaintext value to the plaintext value of the desired option.

**Closed as completed by ProLoser** 2012-12-08 00:52 UTC
