### ISSUE TITLE
CodeMirror display not updated when its model is changed

### ISSUE THREAD

**Issue by s-lip** [angular-ui/angular-ui-OLDREPO#183] opened 2012-08-29 23:30 UTC
Not sure if this is a bug, or if I'm doing something wrong; sorry if it's the latter.

If you go to http://jsfiddle.net/2hHX4/2/ and perform the following steps:
- Click 'Show Console'
- Type stuff in the codemirror box that appears below
- Click 'Hide Console'
- Click 'Delete code' to clear the 'code' model
- Click 'Show Console' again

you'll see that the old contents of 'code' display in the console. This displayed value only gets updated after I click in the codemirror and type something.

Is it possible to update the codemirror so that its displayed value is always synced with the 'code' model?

**Comment by OClement** [comment] 2012-11-06 15:01
I didn't see that issue when I created mine, sorry;

This issue is a duplicate of #245 (#245 having more documentation and description of the issue) 

Not sure if we can mark this one as a dupe

**Comment by ProLoser** [comment] 2012-11-06 20:40
I'm closing this so that the discussion can be merged into #245

**Closed as completed by ProLoser** 2012-11-06 20:40 UTC
