### ISSUE TITLE
Tab headers showing variable name.

### ISSUE THREAD

**Issue by mmosteller** [angular-ui/angular-ui-OLDREPO#384] opened 2013-01-28 18:42 UTC
When I first load up a server and go to my page with tabs it works perfectly. However, when I reload the page it starts showing {{tab.title}} as the tab's header text. Code:

``` javascript
<tabs>
        <pane ng-repeat="tab in tabs" heading="{{tab.title}}">
            <div ng-include src="tab.url"></div>
        </pane>
</tabs>
```

For the controller I have:

``` javascript
function ApplicantTabCtrl($scope) {
    $scope.tabs = 
    [ 
    {title: 'Contact Info', url: 'partials/app-detail-contact.html'},
    {title: 'Application', url: 'partials/app-detail-application.html'} 
    ];
    $scope.tab = $scope.tabs[0];
}
```

Any help will be appreciated, thanks!

**Comment by pkozlowski-opensource** [comment] 2013-01-28 18:50
@mmosteller I guess you wanted to open an issue in this repo: https://github.com/angular-ui/bootstrap

Looking at your description it is not clear what might be going wrong. Could you prepare a plunker with a live scenario to reproduce? You can start with this one: http://plnkr.co/edit/KAYnvV?p=preview

**Comment by pkozlowski-opensource** [comment] 2013-01-28 20:55
@mmosteller played with the code you've attached to the issue report and I really can't seem to reproduce this... Here is the plunker I've used: http://plnkr.co/edit/KAYnvV?p=preview

I'm sure that there is something going on in the code you've got but we can't fix things we can't reproduce...
Going to close this issue for now, please open another one in the https://github.com/angular-ui/bootstrap when you've got a reproduce scenario. Thnx!

**Closed as completed by pkozlowski-opensource** 2013-01-28 20:55 UTC
