### ISSUE TITLE
Update to grunt 0.4

### ISSUE THREAD

**Issue by dmitryevseev** [angular-ui/angular-ui-OLDREPO#491] opened 2013-03-18 07:53 UTC
Currently there is no option to build cloned project.
Grunt is not included in package.json and hence 0.4 version is installed but the project itself uses 0.3.
We can first add `"grunt": "~0.3",` in the devDependencies and upgrade to 0.4 in the future.

**Comment by daspecster** [comment] 2013-03-19 18:38
+1

**Comment by dmitryevseev** [comment] 2013-03-20 17:17
I'd like to help with that one, but lack of feedback stops me now.
Just approve that it fits your intentions and if you mind I'll move on with that in next few days.

**Comment by jdpedrie** [comment] 2013-03-20 17:29
I was playing around with it yesterday, and I got it building build/angular-ui.js from the modules folder. It doesn't minify or work with the comments. I'm also no expert on grunt. Feel free to take a look, and if there's anything worth keeping, keep it.

https://github.com/jdpedrie/angular-ui/commit/3bfd8c6861aad919b3bc079a63c0794cd8e342fa#Gruntfile.js

**Comment by ProLoser** [comment] 2013-03-20 21:10
Anything you guys develop we will more than happily use. The issue is that
with the planned restructuring, the build process is going to change.

If you guys are interested in helping out, I can add both of you to the
build team and perhaps you can help develop the new build solution which we
ideally want to use across all projects.

At this moment the primary concern is actually generating the docs.

**Comment by dmitryevseev** [comment] 2013-03-20 21:15
Sounds great.
Thank you for making priorities clear. Will be glad to help

**Comment by ProLoser** [comment] 2013-03-20 21:48
https://groups.google.com/forum/?fromgroups=#!category-topic/angular-ui/JHufs1VlJf4

**Comment by 0x-r4bbit** [comment] 2013-03-22 22:01
Already something in the making right here? I'd also get on the boat.

**Comment by dmitryevseev** [comment] 2013-03-22 22:37
Hi @PascalPrecht . As Dean said, there is a discussion in progress in groups.
It involves decisions on source files structure and grunt update is postponed untill UI team has clear solution on that. Feel free to join

**Comment by 0x-r4bbit** [comment] 2013-03-22 22:44
Thank you sir!

**Comment by ProLoser** [comment] 2013-03-22 22:46
You guys are more than encouraged to provide input on the thread as it's currently being a big fucking blocker for me. I might just be too lazy to create a docs generator.

**Comment by ProLoser** [comment] 2013-03-23 01:13
Your missions should you choose to accept it:

Create a docs-generator here https://github.com/angular-ui/angular-ui-docs

It must be able to load into a standalone plugin (ui-select2 and ui-date) and we will try to re-use some of the code for angular-ui (which will have a built version of ui-select2 and date, etc).

I'm getting burned out over this docs generator so for now i think i'm just going to hardcode shit.

**Comment by inklesspen** [comment] 2013-03-26 18:00
Grunt now requires you to install grunt-cli for the grunt command; thus the README should be updated.

**Comment by ProLoser** [comment] 2013-09-09 00:26
Closing this issue. Feel free to open one on https://github.com/angular-ui/angular-ui-docs

**Closed as completed by ProLoser** 2013-09-09 00:26 UTC
