### ISSUE TITLE
ui-date="{showOn: 'button'}" breaking

### ISSUE THREAD

**Issue by ajoslin** [angular-ui/angular-ui-OLDREPO#109] opened 2012-07-23 13:02 UTC
http://stackoverflow.com/questions/11611655/angular-ui-datepicker-seems-to-hang-angularjs-when-showing-button

**Comment by petebacondarwin** [comment] 2012-07-23 13:07
Commented on SO

On 23 July 2012 14:02, Andy Joslin <
reply@reply.github.com

**Comment by ProLoser** [comment] 2012-07-23 18:08
I'd like everyone to please read my response to this question:
http://stackoverflow.com/questions/11611655/angular-ui-datepicker-seems-to-hang-angularjs-when-showing-button/11617982#11617982

We need to change the other directives to coincide. I was sort of 'hoping'
that this problem wasn't present for the Datepicker.

On Mon, Jul 23, 2012 at 6:02 AM, Andy Joslin <
reply@reply.github.com

**Comment by ProLoser** [comment] 2013-02-15 11:05
I know this sounds horrid but to compensate for this bug should we fire the datepicker in a $timeout when the option is set to button?

**Comment by petebacondarwin** [comment] 2013-02-15 12:13
I don't like the idea of using timeouts.  By the way a halfway house would
be to put it in the $scope.evalAsynch queue possibly.  But better would be
to add a dummy element in the compile function to account for jQuery adding
items in the link function.  By the way, it is WAY worse if it added the
item "before" the current one!

**Comment by petebacondarwin** [comment] 2013-02-15 12:29
Actually I just checked.  Because all the work is now done in a $watch the jQuery date widget is not run until the first digest, which is after the compile has finished, and so this bug is now fixed.
Here is a Plnkr to prove it: http://plnkr.co/edit/nPmxJJMkceS7tqVSZKh7?p=preview.
But we should write a unit test to prevent regression.

**Closed as completed by petebacondarwin** 2013-02-15 12:29 UTC

**Comment by petebacondarwin** [comment] 2013-02-15 12:45
Fixed in 0.4.0 and just added a regression test to master.
