### ISSUE TITLE
ui-keypress requires ng-model-instant to update model

### ISSUE THREAD

**Issue by dandoyon** [angular-ui/angular-ui-OLDREPO#8] opened 2012-04-01 06:00 UTC
This will not be self-evident that ng-model-instant is needed. Probably want something like in ui-date that does $setViewValue

**Comment by dandoyon** [comment] 2012-04-02 04:44
I was thinking about this today and it occurred to me that you probably don't want to have ng-model instant, mainly because this is generic and there can be other things than enter key. Then it occurred to me that I should ask the question as to what this directive is for? If it is primarily for handling enter key, which angular doesn't do, then I would say it should be just that. This would simplify the api. I would like to know other use cases for having generic keypress.

**Comment by ProLoser** [comment] 2012-04-02 20:29
This doesn't actually use ng-model in any capacity. It simply binds to the keypress event of the specified element. I am not using $watch as this is triggered by angular and contains no information about the triggering event.

The main reason I wanted this was so that hitting [return] on a textarea submits the form, but it's designed so people can use it for whatever. I may want to look to enhance it to catch modifier keys + characters (like ctrl+b or something).

Is it not working for you?

**Comment by ProLoser** [comment] 2012-04-02 20:30
I just realized that this _might_ cause unusual behavior if, like you said, you need to modify the model value (or inputs value). I'm not sure what the order of execution is or what would occur.

**Comment by dandoyon** [comment] 2012-04-03 04:40
Given the broadness of this, I might suggest two things
1. create something like ui-enter (or ui-accept-on-enter). With this directive you make it dead simple and when enter key is hit it updates model with an optional method to be executed. It would have to be clear as to when that method is executed (before or after the model is updated). There is another issue that needs to be considered which (and I believe ng-model-instant takes care of) is updating the model on blur. 
2. Could still have ui-keypress but it could be a more advanced control that also takes a key an optional method and then of course the modifiers. 

In both of these cases, not sure if there is a conflict to updating model but then what if there is an ng-model-instant directive?

So you would have &lt;input ng-model="foo" ui-enter&gt; or &lt;input ng-model="foo" ui-enter="dosomething"&gt; 
&lt;input ng-model="foo" key="b" modifier="ctrl"&gt;

IMHO, I think if you have a finite number of options (three or less) then it is better than one param or one options object. 

On side note, I spent a bit of time this weekend trying to do a unit test, but was unsuccessful mocking the keypress handler function to register as being called. I'd really like to have tests backing things but am finding gaps of knowledge on jasmine + angular. Oh well... am going to post a question on angular-dev

**Comment by ProLoser** [comment] 2012-04-03 07:47
I'm sort of confused. The directive works perfectly fine for me. The issue is introduced when you attempt to start modifying the value of ng:model, however I'm 1: not trying to do that and 2: dealing with similar issues everywhere else in angular completely independent of this one scenario. WYSIWYG maxlength is my current problem.

I figure if someone wants to use the callback to modify the value, he can worry about the problems that arrise himself, especially since I don't know how to circumvent them myself nor did I ever specify that the directive was responsible for this.

Again, I'm not exactly sure what you want to DO with the value, but if you want to modify it that opens many new questions which I never even felt like starting addressing (should this fire a watch? should it fire after the watch? before? etc). The one part I would concede is a better way to pass multiple arguments, however I've been quite fond of my approach of treating directives like functions and passing arguments together to reduce long directive names.

**Comment by dandoyon** [comment] 2012-04-03 16:34
Sorry if I'm being a thorn, I think the solution to the updating of the model is probably through documentation as a caveat. This is a nice directive to compensate for the missing bits in angular.  Me and my colleagues beat up any potential apis we're looking to create in an attempt to  "measure twice, cut once". Oftentimes, I encounter an api that has not be well thought out and i end up scratching out what little hair i have left.  

BTW:  thought this simple app was pretty nice to have kicking around. http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

--dan

**Comment by ProLoser** [comment] 2012-05-24 22:34
Which release-candidate was this fixed in? We can probably close this for the latest one.

**Closed as completed** 2012-05-27 23:25 UTC
