### ISSUE TITLE
Double Click to Edit Directive?

### ISSUE THREAD

**Issue by leeola** [angular-ui/angular-ui-OLDREPO#440] opened 2013-02-17 21:04 UTC
I've been looking to add double-click to edit functionality to one of my apps, and thought AngularUI would have this functionality out of the box, but i don't see it anywhere.

Is this sort of feature error prone/complicated in many use cases? Or has it simply not been added by anyone.

Either way, consider this a request for this feature, and feel free to discuss any specifics of it that i might be missing.. perhaps it doesn't really work well when made as a directive.

In case there is any confusion on what this feature is.. The simple idea is that you have an text element which you double click, and upon double clicking the element is replaced with an input field, allowing you to replace/change the text. Example: http://jsfiddle.net/YzD3H/9/

**Comment by ProLoser** [comment] 2013-02-17 23:30
Duplicate of #324

**Comment by wesleycho** [comment] 2013-09-09 00:21
`ng-dblclick` is in Angular (perhaps you need to use the unstable version) - the code is available in `ngEventDirs.js` in the Angular source if you need it separate from Angular UI.  This repository is discontinued though.

**Closed as completed by wesleycho** 2013-09-09 00:21 UTC
Labels: request
