### ISSUE TITLE
Event not passed to the Keypress directive

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular-ui/angular-ui-OLDREPO#57] opened 2012-07-14 18:02 UTC
hi!

First of all, thnx for all the work on the angular-ui!

It looks like the original event is not passed into the Keypress directive so it is impossible to call `e.preventDefault()`. The problem is visible on the angular-ui [demo page(http://angular-ui.github.com/#directives-keypress) where pressing Enter moves to a new line in a text editor. Can prepare a jsFiddle with an example if needed to reproduce.

From what I can see the pb was introduced in the c15c6fd7 (with a major refactoring). 

Cheers,
Pawel

**Comment by ProLoser** [comment] 2012-07-14 19:39
I'm completely aware that it occurs and I figured I would update the documentation to not try e.preventdefault. the issue is that before you would pass the name of a function I could execute and therefore pass whatever I want to. The refactor now let's you simply execute angular expressions (similar to how ng-click and change is done) but since I no longer have direct access to a function I cannot pass custom params to it easily. The challenge them becomes how to solve this elegantly. 

You know what? I just thought of how to solve this. I can set an $event object that people can leverage how they wish. 

pkozlowski-opensource reply@reply.github.com wrote:

hi!

First of all, thnx for all the work on the angular-ui!

It looks like the original event is not passed into the Keypress directive so it is impossible to call `e.preventDefault()`. The problem is visible on the angular-ui [demo page(http://angular-ui.github.com/#directives-keypress) where pressing Enter moves to a new line in a text editor. Can prepare a jsFiddle with an example if needed to reproduce.

From what I can see the pb was introduced in the c15c6fd7 (with a major refactoring). 

Cheers,
Pawel

---

Reply to this email directly or view it on GitHub:
https://github.com/angular-ui/angular-ui/issues/57

**Comment by pkozlowski-opensource** [comment] 2012-07-14 19:46
Good, exposing $event would be consistent with other angular.js directives (for example http://docs.angularjs.org/api/ng.directive:ngMousedown and other directives of this family).

I guess it would be rather simple to code by I was a bit surprised that I couldn't find test for this directive... Anyway, as I have said, I can help with this one or just have your fix :-)

**Comment by ProLoser** [comment] 2012-07-14 19:47
Holy crap,  Andy already thought of this and fixes it in #55

**Comment by ProLoser** [comment] 2012-07-16 00:32
Pinging @borodiychuk for this one. I started converting this to pass the $event object just like uiEvent does, however I ran into a few problems when working with the demo:
1. The event is binded to keydown. It is impossible to preventDefault() on this event.
2. It is impossible to handle multiple keys simultaneously in keypress, keydown must be used.

For this reason I think you should add 2 more variations to this directive:

ui-keypress, for common behavior, but only support a single key
ui-keydown, for multiple key behavior
ui-keyup, for any other cases

You can keep all 3 cases in the same file as different directives since they are slow closely related. It would also be ideal to get as much DRY reuse as possible out of the code. @borodiychuk do you think you'd be willing to do this refactor?

**Comment by ProLoser** [comment] 2012-07-16 00:33
FYI - this is how to pass the $event to the expression for use (taken from uiEvent):

```
var fn = $parse(combination.expression);
scope.$apply(function() {
    fn(scope, { '$event' : event });
});
```

You must inject the `$parse` service

**Comment by pkozlowski-opensource** [comment] 2012-07-16 19:46
hi! Sorry, just tested the fix from 575c62e and it doesn't work :-( BTW: the example on the angular-ui page is also broken.

 In fact the Scope.$apply will always call a passed in-function with only one argument (scope) so I'm not sure how `scope.$apply(combination.expression, { '$event' : event });` could work :-(

I've checked also Andy's implementation of the event directive and it is quite different from the keypress one... I will look at the source code to see how this be fixed but for now just reopening the issue.

**Comment by pkozlowski-opensource** [comment] 2012-07-16 19:48
OK, just realized that I can't re-open it, it would be great if someone could look into my comment above and decide if this one should be re-opened or it is just me struggling with the proper usage....

**Comment by ProLoser** [comment] 2012-07-18 21:23
Closing this because @pkozlowski-opensource is awesome

**Closed as completed by ProLoser** 2012-07-18 21:23 UTC
