### ISSUE TITLE
date does not work on chrome if input type=date

### ISSUE THREAD

**Issue by hyusetiawan** [angular-ui/angular-ui-OLDREPO#296] opened 2012-12-06 01:11 UTC
chrome came out with its own datepicker by defining input type="date". Unfortunately, it conflicts with angularui's date

the setup is simple:

```
<input type="date" ui-date  ng-model="store.to" />
```

and the value of store.to will be null

**Comment by ProLoser** [comment] 2012-12-06 02:08
Duplicate of #230

**Closed as completed by ProLoser** 2012-12-06 02:08 UTC
